### ISSUE TITLE
Issues.

### ISSUE THREAD

**Issue by Drup** [sheijk/ppx_string_interpolate#1]
1) [This](https://github.com/sheijk/ppx_string_interpolate/blob/3280b915ecc746964177c41c6043b994fb9d88ff/META#L4) is broken, for completely obvious reasons. You should point to the path _once installed_
2) You only build the native version, even when it's not possible
3) You build it with ".native" prefix and install it like that. It's unidiomatic both on windows _and_ linux.

Two to three of this issues would be avoided with a proper build/packaging system.
If you are going to use a makefile, at least use OCamlMakefile, not a crappy broken homegrown one.

**Comment by sheijk** [comment]
1 and 3 are addressed in 5c159264a23c7f47c8692e9afdf8efbe079a34fa.

For 2 I'll need to have a look at how opam/ocamlfind decide whether to use the byte code or native version of a ppx preprocessor. And maybe move to another build system.
